version: '3.4'

services:
  web:
    build: ./docker/php
    container_name: "${APP_NAME}_web"
    ports:
      - "9000:9000"
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: 9003
    volumes:
      - ./api:/var/www
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: "${APP_NAME}_nginx"
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_db
      MYSQL_USER: backend_user
      MYSQL_PASSWORD: backend_password
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
